### ISSUE TITLE
安卓每次退出APP，会报一个错

### ISSUE THREAD

**Issue by vjHuang** [v7lin/wechat_kit#46]
java.lang.RuntimeException: Unable to destroy activity {com.*/com.*.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.Context.unregisterReceiver(android.content.BroadcastReceiver)' on a null object reference

相关代码都还没写，只是在pubspec.xml中引入，都会这样。

**Comment by v7lin** [comment]
这个有点尴尬了，我明天发个版本修正一下

**Comment by vjHuang** [comment]
好的，有劳了

**Comment by vjHuang** [comment]
更新到pub了吗？

**Comment by vjHuang** [comment]
话说我的pub，时不时的打不开，翻墙也没用，你们会这样吗

**Comment by v7lin** [comment]
更新了

```shell
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
export PATH=$PATH:~/flutter/bin
export PATH=$PATH:$HOME/.pub-cache/bin
```

**Comment by vjHuang** [comment]
好的，谢谢
